### ISSUE TITLE
child_process package

### ISSUE THREAD

**Issue by saiaman** [dominant-strategies/hardhat-example#16]
Please don't use a npm package for this child_process : 

const util = require('node:util');
const spawn = util.promisify(require('node:child_process').spawn);

and then use spawn as you use it actually

**Comment by Juuddi** [comment]
What is the downside to use an npm package for this? I'm not incredibly familiar with process spawning so I'm up to change it, just want to understand the reasoning.

**Comment by Juuddi** [comment]
Closing this as the usage of `child-process` for multi-chain deploys has been removed from this repo.
