### ISSUE TITLE
Deployment is not working

### ISSUE THREAD

**Issue by dani-s-92** [dominant-strategies/hardhat-example#23]
Hello,
if I try to compile Greeter contract on a single chain, I get the following error:
`npx hardhat compile`
`Error HH505: A native version of solc failed to run.`

`If you are running MacOS, try installing Apple Rosetta.`

`If this error persists, run "npx hardhat clean --global".`

`For more info go to https://hardhat.org/HH505 or run Hardhat with --show-stack-traces`

Does someone know the issue? What do I have to do to get it running? 
Thank you!

**Comment by Juuddi** [comment]
Closing this as it is no longer relevant.
